routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/add/{id}',[HomeController::class,'add'])->name('home.add');
Route::get('/show',[HomeController::class,'show'])->name('home.show');
Route::get('/destroy/{id}',[HomeController::class,"destroy"])->name('home.destroy'); 
Route::get('/clear}',[HomeController::class,"clear"])->name('home.clear'); 
Route::get('/clientInfo}',[HomeController::class,"clientInfo"])->name('home.clientInfo'); 
Route::post('/storeInfo}',[HomeController::class,"storeInfo"])->name('home.storeInfo'); 
Route::get("categorie/search",[CategorieController::class,'search'])->name("categories.search");
Route::get("produit/search",[ProduitController::class,'search'])->name("produits.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Include the noUiSlider stylesheet -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.6.4/nouislider.min.css">


    <title>@yield('title', 'App store')</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="{{ route('home.index') }}">Accueil</a></li>
            <li><a href="{{ route('categories.index') }}">Gestion des categories</a></li>
            <li><a href="{{ route('produits.index') }}">Gestion des produits</a></li>
            <li><a href="#">Gestion des commande</a></li>
            <li><a href="{{route("home.show")}}">View cart</a></li>
            <li><a href="#">mes commande</a></li>
        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
    <!-- Include the noUiSlider JavaScript library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.6.4/nouislider.min.js"></script>
<script src="{{asset("js/main.js")}}"></script>
</body>

</html>