routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/add/{id}',[HomeController::class,'add'])->name('home.add');
Route::get('/show',[HomeController::class,'show'])->name('home.show');
Route::get('/destroy/{id}',[HomeController::class,"destroy"])->name('home.destroy'); 
Route::get('/clear}',[HomeController::class,"clear"])->name('home.clear'); 
Route::get('/clientInfo}',[HomeController::class,"clientInfo"])->name('home.clientInfo'); 
Route::post('/storeInfo}',[HomeController::class,"storeInfo"])->name('home.storeInfo'); 
Route::get("categorie/search",[CategorieController::class,'search'])->name("categories.search");
Route::get("produit/search",[ProduitController::class,'search'])->name("produits.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'image'
    ];
    public function categorie(){
       return  $this->belongsTo(Categorie::class);
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $produitsBuilder = Produit::query();

        $designation = $request->query("filter_designation");
        $categorie = $request->query("filter_categorie");
        $prix_u_min = $request->query("prix_u_min");
        $prix_u_max = $request->query("prix_u_max");
        $quantite = $request->query("filter_quantite_stock");

        if ($designation != null) {
            $produitsBuilder->where('designation', 'like', '%' . $designation . '%');
        }
        if ($categorie != null) {
            $produitsBuilder->where('categorie_id', $categorie);
        }
        if ($prix_u_min != null) {
            $produitsBuilder->where('prix_u', '>=', $prix_u_min);
        }

        if ($prix_u_max != null) {
            $produitsBuilder->where('prix_u', '<=', $prix_u_max);
        }

        if ($quantite != null) {
            $produitsBuilder->where('quantite_stock', '=', $quantite);
        }
        $param = [
            "filter_designation" => $designation,
            "filter_categorie" => $categorie,
            "prix_u_min" => $prix_u_min,
            "prix_u_max" => $prix_u_max,
            "filter_quantite_stock" => $quantite
        ];
        if(!$produitsBuilder){}
        $produits = $produitsBuilder->paginate(5)->appends($param);

        $categories = Categorie::all();
        return view("produits.index", [
            'produits' => $produits,
            "categories" => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */


    public function create()
    {
        $categories = Categorie::all();
        return view("produits.create", compact("categories"));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validateData=$request->validate([
            "designation" => "required|unique:produits,designation",
            "prix_u" => "required",
            "quantite_stock" => "required",
            "categorie_id" => "required",
            "image"=>"image|mimes:jpeg,png,jpeg,gif,svg|max:2048"
        ]);
       
        if($request->hasFile("image")){
            $imagePath=$request->file("image")->store("products/images","public");
            $validateData["image"]= $imagePath;
        }
        Produit::create($validateData);
        return redirect()->route("produits.index");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $produit = Produit::find($id);

        return view('produits.show')->with("produit", $produit);

        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $produit = Produit::find($id);
        $produits = Produit::all();
        return view('produits.edit', compact('produit', "produits"));

        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            "designation" => "required|unique:prouduits,designation," . $id,
            "prix_u" => "required",
            "quantite_stock" => "required",
            "categorie_id" => "required",
            "image"=>"image|mimes:jpeg|png|jpeg|gif|svg|max:2048"

        ]);
        $produit = Produit::find($id);
        $produit->update($request->all());
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');
    }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
@section('title', 'cree un produit')
@section('content')
    <h1>Ajouter un produit</h1>
    <form action="{{ route('produits.store') }}" method="post"  enctype="multipart/form-data">
        @csrf
        <div>
            <label for="designation">Designation</label>
            <input type="text" name="designation" value="{{old("designation")}}">
        </div>
        <div>
            <label for="prix_u">Prix unitaire</label>
            <input type="number" min="1" name="prix_u" id="prix_u" value="{{old("prix_u")}}">
            <span>DH</span>

        </div>
        <div>
            <label for="quantite_stock">Quantite on stock</label>
            <input type="number" min="0"  name="quantite_stock" id="quantite_stock" value="{{old("quantite_stock")}}">
        </div>
        <div>
            <label for="categorie_id">N° Categorie</label>
            <select name="categorie_id" id="categorie_id">
                <option value="">Select la categorie -----------</option>
                @foreach ($categories as $categorie)
                    <option value="{{ $categorie->id }}">{{ $categorie->id }} - {{ $categorie->designation }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <input type="file" name="image" id="image" accept="image/*">
        </div>
        <div>
            <input type="submit" value="Ajouter">
            <input type="reset" value="Vider">
        </div>
        
    </form>
    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li>{{$error}}</li>
        @endforeach
    </ul>
    @endif
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
@section('title', 'Modifier un produit')
@section('content')
    <h1>Modifier un produit</h1>
    <form action="{{ route('produits.update',["produit"=>$produit->id])}}" method="post">
        @method("put")
        @csrf
        <div>
            <label for="designation">Designation</label>
            <input type="text" name="designation" value="{{$produit->designation}}">
        </div>
        <div>
            <label for="prix_u">Prix unitaire</label>
            <input type="number" min="1" name="prix_u" id="prix_u" value="{{$produit->prix_u}}">
            <span>DH</span>

        </div>
        <div>
            <label for="quantite_stock">Quantite on stock</label>
            <input type="number" min="0"  name="quantite_stock" id="quantite_stock" value="{{$produit->quantite_stock}}">
        </div>
        <div>
            <label for="categorie_id">N° Categorie</label>
            <select name="categorie_id" id="categorie_id">
                <option value="">Select la categorie -----------</option>
                @foreach ($produits as $produit)
                    <option value="{{ $produit->id }}">{{ $produit->id }} - {{ $produit->designation }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <input type="submit" value="Modifier">
            <input type="reset" value="Vider">
        </div>
    </form>
    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li>{{$error}}</li>
        @endforeach
    </ul>
    @endif
@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
@section('title', 'Gestion des produits')
@section('content')
    <h1>Liste des Produits</h1>
    <form action="{{ route('produits.index') }}" method="get" >
        <div>
            <label for="filter_designation">Designation : </label>
            <input type="text" id="filter_designation" name="filter_designation" placeholder="Filtre par Designation"
                value="{{ isset($param) ? $param : '' }}">
        </div>
        <div>
            <label for="filter_categorie">Categorie : </label>
            <select name="filter_categorie" id="filter_categorie">
                @foreach ($categories as $cat)
                <option value="{{$cat->id}}">{{$cat->designation}}</option>
                @endforeach
            </select>
           
        </div>
        <div>
            <label for="prix_u">Prix : </label>
            <input type="hidden" name="prix_u_min" id="prix_u_min">
            <input type="hidden" name="prix_u_max" id="prix_u_max">
            <!--   ----------------------   -->
            <span id="lower-price">0</span>MAD
            <div id="price-range-slider">
            </div>
            <span id="upper-price">1000</span>MAD
        </div>

        <!--   ----------------------   -->

        <div>
            <label for="filter_quantite_stock">Quantite en stock : </label>
            <input type="text" id="filter_quantite_stock" name="filter_quantite_stock" placeholder="Filtre par Quantite en stock"
                value="{{ isset($param) ? $param : '' }}">
        </div>
        

        <input type="submit" value="Appliquer" name="search" >
    </form>
    <table id="tbl">
        <div>
            <a href="{{ route('produits.create') }}">Ajouter un noveau produit</a>
        </div>
        <tr>
            <th>ID</th>
            <th>Designation</th>
            <th>Prix unitaire</th>
            <th>Quantite on stock</th>
            <th>N° Categorie</th>
            <th colspan="3">Action</th>
        </tr>
        @foreach ($produits as $produit)
            <tr>
                <td>{{ $produit->id }}</td>
                <td>{{ $produit->designation }}</td>
                <td>{{ $produit->prix_u }}</td>
                <td>{{ $produit->quantite_stock }}</td>
                <td>{{ $produit->categorie_id }} - {{$produit->Categorie->designation}}</td>
                <td><a href="{{ route('produits.show', ['produit' => $produit->id]) }}">Details</a></td>
                <td><a href="{{ route('produits.edit', ['produit' => $produit->id]) }}">Modifier</a></td>
                <td>
                    <form action="{{ route('produits.destroy', ['produit' => $produit->id]) }}" method="post">
                        @method('DELETE')
                        @csrf
                        <input type="submit"
                            onclick="return confirm('voulez vous supprimer le produit ayant lid {{ $produit->id }}')"
                            value="supprimer">
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
    <div>
        {{ $produits->links() }}
    </div>
@endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
@section('title','Detail d \'une categorie')
@section('content')
   <a href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
   <h1>Detail de le produit Num {{$produit->id}}</h1>
   <div>
       <p><strong>Designation:</strong> {{$produit->designation}}</p>
       <p><strong>Prix unitaire:</strong> {{$produit->prix_u}}</p>
       <p><strong>Quantite on stock:</strong> {{$produit->quantite_stock}}</p>
       <p><strong>N° Categorie:</strong> {{$produit->categorie_id}}</p>
       <p>image</p>
       <img src="{{asset('storage/'. $produit->image)}}" alt="{{$produit->designation}}">
   </div>
@endsection